version: "3"

    api1:
        container_name: api1
        image: api1:${TAG:-latest}
        build:
            context: ./api1
            dockerfile: Dockerfile
        command: sh -c "yarn start"
        ports:
        - 9000:9000
        expose: 
        - 9000
        volumes:
        - ./api1/:/api1
  
        environment:
            NAME: ${API1_NAME}
            PORT: ${API1_PORT}

    api2:
        image: api2:${TAG:-latest}
        build:
            context: ./api2
            dockerfile: Dockerfile
        command: sh -c "yarn start"
        ports:
        - 3000:3000
        volumes:
        - ./api2/:/api2
        depends_on:
        - api1
        links: 
        - api1
        environment:
            NAME: ${API2_NAME}
            PORT: ${API2_PORT}
            API1_HOST: ${API1_HOST}
            
            
    
